In [7]:
import pandas as pd
import numpy as np

In [8]:
pd.set_option('display.max_columns', None)

In [9]:
avg_annual_daily=pd.read_excel('C:/Users/ritun/Desktop/MSc Data Science University of Bristol/Data Science Mini Project/Traffic Datasets/Bristol Traffic Data/Average annual daily flow(At various count points).xlsx')

In [10]:
avg_annual_daily.drop('Unnamed: 0', inplace=True, axis=1)

In [11]:
avg_annual_daily

,count_point_id,year,region_id,region_name,local_authority_id,local_authority_name,road_name,road_type,start_junction_road_name,end_junction_road_name,easting,northing,latitude,longitude,link_length_km,link_length_miles,estimation_method,estimation_method_detailed,pedal_cycles,two_wheeled_motor_vehicles,cars_and_taxis,buses_and_coaches,lgvs,hgvs_2_rigid_axle,hgvs_3_rigid_axle,hgvs_4_or_more_rigid_axle,hgvs_3_or_4_articulated_axle,hgvs_5_articulated_axle,hgvs_6_articulated_axle,all_hgvs,all_motor_vehicles
0,946809,2014,1,South West,144,"Bristol, City of",U,Minor,NaN,NaN,362151,175877,51.480576,-2.546420,NaN,NaN,Counted,Manual count,2,1,117,0,8,0,0,0,0,0,0,0,127
1,27877,2014,1,South West,144,"Bristol, City of",A4174,Major,A37,A4,361000,170060,51.428196,-2.562350,1.5,0.93,Estimated,Estimated using previous year's AADF on this link,119,126,14408,104,2687,424,141,88,8,34,112,806,18132
2,27728,2014,1,South West,144,"Bristol, City of",A4162,Major,A4,Canford Rd,355000,177040,51.490507,-2.649537,2.5,1.55,Estimated,Estimated using previous year's AADF on this link,34,82,4403,48,769,70,17,21,1,2,4,115,5417
3,46408,2014,1,South West,144,"Bristol, City of",A4044,Major,A38,A4/B4053 roundabout,359300,172400,51.449115,-2.587071,0.4,0.25,Estimated,Estimated using previous year's AADF on this link,975,123,6853,687,1242,113,37,24,1,3,16,194,9099
4,946747,2014,1,South West,144,"Bristol, City of",B4052,Minor,NaN,NaN,359779,174780,51.470548,-2.580450,NaN,NaN,Counted,Manual count,448,208,14783,34,2699,82,9,9,2,1,0,103,17828
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,28726,2020,1,South West,144,"Bristol, City of",A4,Major,A3029,A4 split,357000,172591,51.450660,-2.620190,0.4,0.25,Estimated,Estimated using previous year's AADF on this link,416,275,12275,247,2019,116,46,106,11,15,11,306,15121
1006,38142,2020,1,South West,144,"Bristol, City of",A38,Major,Bedminster Down Rd,A4174,357758,170488,51.431809,-2.609031,0.5,0.31,Estimated,Estimated using previous year's AADF on this link,97,175,12119,114,2940,233,36,60,10,39,39,417,15764
1007,26128,2020,1,South West,144,"Bristol, City of",A3029,Major,A4,A370,356750,172000,51.445328,-2.623715,0.5,0.31,Counted,Manual count,266,647,37050,260,9469,606,231,411,121,174,229,1773,49199
1008,28348,2020,1,South West,144,"Bristol, City of",A420,Major,Clarence Rd,Stapleton Rd,360040,173410,51.458247,-2.576537,0.2,0.12,Counted,Manual count,135,199,6084,294,1402,75,17,0,3,6,3,102,8083
1009,92038,2020,1,South West,144,"Bristol, City of",A4044,Major,lat: 51.449 long: -2.5903,lat: 51.4488 long: -2.5842,359297,172382,51.448951,-2.587112,0.4,0.25,Estimated,Estimated using previous year's AADF on this link,1729,168,5217,373,985,72,11,7,2,8,6,106,6849

Checking info about the dataset:

In [12]:
avg_annual_daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   count_point_id                1010 non-null   int64
 1   year                          1010 non-null   int64
 2   region_id                     1010 non-null   int64
 3   region_name                   1010 non-null   object
 4   local_authority_id            1010 non-null   int64
 5   local_authority_name          1010 non-null   object
 6   road_name                     1010 non-null   object
 7   road_type                     1010 non-null   object
 8   start_junction_road_name      715 non-null    object
 9   end_junction_road_name        715 non-null    object
 10  easting                       1010 non-null   int64
 11  northing                      1010 non-null   int64
 12  latitude                      1010 non-null   float64
 13  longitude                     1010 non-null   float64
 14  link_length_km                715 non-null    float64
 15  link_length_miles             715 non-null    float64
 16  estimation_method             1010 non-null   object
 17  estimation_method_detailed    1010 non-null   object
 18  pedal_cycles                  1010 non-null   int64
 19  two_wheeled_motor_vehicles    1010 non-null   int64
 20  cars_and_taxis                1010 non-null   int64
 21  buses_and_coaches             1010 non-null   int64
 22  lgvs                          1010 non-null   int64
 23  hgvs_2_rigid_axle             1010 non-null   int64
 24  hgvs_3_rigid_axle             1010 non-null   int64
 25  hgvs_4_or_more_rigid_axle     1010 non-null   int64
 26  hgvs_3_or_4_articulated_axle  1010 non-null   int64
 27  hgvs_5_articulated_axle       1010 non-null   int64
 28  hgvs_6_articulated_axle       1010 non-null   int64
 29  all_hgvs                      1010 non-null   int64
 30  all_motor_vehicles            1010 non-null   int64
dtypes: float64(4), int64(19), object(8)
memory usage: 244.7+ KB

Checking null values:

In [13]:
avg_annual_daily.isnull().any()

count_point_id                  False
year                            False
region_id                       False
region_name                     False
local_authority_id              False
local_authority_name            False
road_name                       False
road_type                       False
start_junction_road_name         True
end_junction_road_name           True
easting                         False
northing                        False
latitude                        False
longitude                       False
link_length_km                   True
link_length_miles                True
estimation_method               False
estimation_method_detailed      False
pedal_cycles                    False
two_wheeled_motor_vehicles      False
cars_and_taxis                  False
buses_and_coaches               False
lgvs                            False
hgvs_2_rigid_axle               False
hgvs_3_rigid_axle               False
hgvs_4_or_more_rigid_axle       False
hgvs_3_or_4_articulated_axle    False
hgvs_5_articulated_axle         False
hgvs_6_articulated_axle         False
all_hgvs                        False
all_motor_vehicles              False
dtype: bool

Checking for duplicates:

In [14]:
avg_annual_daily.duplicated().any()

False

Exporting dataset as csv:

In [16]:
#avg_annual_daily.to_csv("C:/Users/ritun/Desktop/MSc Data Science University of Bristol/Data Science Mini Project/CLEANED DATA/Traffic Data/avg_annual_daily.csv")