In [5]:
import pandas as pd
import numpy as np

In [6]:
pd.set_option('display.max_columns', None)

In [7]:
avg_annual_daily_direc=pd.read_excel('C:/Users/ritun/Desktop/MSc Data Science University of Bristol/Data Science Mini Project/Traffic Datasets/Bristol Traffic Data/Average annual daily flow by direction(At various count points).xlsx')

In [9]:
avg_annual_daily_direc.drop('Unnamed: 0', inplace=True, axis=1)

In [10]:
avg_annual_daily_direc

,count_point_id,year,region_id,region_name,local_authority_id,local_authority_name,road_name,road_type,start_junction_road_name,end_junction_road_name,easting,northing,latitude,longitude,link_length_km,link_length_miles,estimation_method,estimation_method_detailed,direction_of_travel,pedal_cycles,two_wheeled_motor_vehicles,cars_and_taxis,buses_and_coaches,lgvs,hgvs_2_rigid_axle,hgvs_3_rigid_axle,hgvs_4_or_more_rigid_axle,hgvs_3_or_4_articulated_axle,hgvs_5_articulated_axle,hgvs_6_articulated_axle,all_hgvs,all_motor_vehicles
0,16959,2014,1,South West,144,"Bristol, City of",A3029,Major,A38,A3029 Ashton Road/Winterstoke Underpass,357000,170955,51.435953,-2.619990,1.7,1.06,Estimated,Estimated using previous year's AADF on this link,E,79,242,12191,37,2855,259,72,48,25,75,76,556,15882
1,946742,2014,1,South West,144,"Bristol, City of",B4054,Minor,NaN,NaN,353795,177022,51.490248,-2.666889,NaN,NaN,Counted,Manual count,E,27,61,3802,80,562,18,2,0,0,2,0,22,4527
2,946742,2014,1,South West,144,"Bristol, City of",B4054,Minor,NaN,NaN,353795,177022,51.490248,-2.666889,NaN,NaN,Counted,Manual count,W,47,80,3274,78,434,27,5,0,0,0,1,33,3899
3,946765,2014,1,South West,144,"Bristol, City of",U,Minor,NaN,NaN,357754,175691,51.478591,-2.609711,NaN,NaN,Counted,Manual count,E,63,1,288,0,39,2,0,0,0,0,0,2,330
4,946765,2014,1,South West,144,"Bristol, City of",U,Minor,NaN,NaN,357754,175691,51.478591,-2.609711,NaN,NaN,Counted,Manual count,W,51,1,157,0,26,0,0,0,0,0,0,0,185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1863,28420,2020,1,South West,144,"Bristol, City of",A432,Major,B4469,A4174,364000,176170,51.483329,-2.519826,2.6,1.62,Estimated,Estimated using previous year's AADF on this link,E,297,31,2862,35,510,40,18,2,2,5,4,71,3508
1864,28420,2020,1,South West,144,"Bristol, City of",A432,Major,B4469,A4174,364000,176170,51.483329,-2.519826,2.6,1.62,Estimated,Estimated using previous year's AADF on this link,W,389,56,3569,38,590,56,5,0,1,3,5,69,4322
1865,36133,2020,1,South West,144,"Bristol, City of",A4,Major,A4176 Bridge Valley road,A3029 Brunel Way,356669,172593,51.450653,-2.624953,1.4,0.87,Counted,Manual count,N,28,169,11218,111,2576,252,64,123,28,36,190,693,14766
1866,58285,2020,1,South West,144,"Bristol, City of",A3029,Major,A3029 Brunel Lock Road/McAdam Way,A4 midpoint,356840,172360,51.448571,-2.622464,0.2,0.12,Counted,Manual count,S,36,248,18620,17,3422,268,70,168,8,66,101,681,22988
1867,73300,2020,1,South West,144,"Bristol, City of",A369,Major,A370/A3029 midpoint,LA Boundary,356490,172000,51.445308,-2.627456,0.9,0.56,Estimated,Estimated using previous year's AADF on this link,S,43,45,3296,32,692,17,4,0,1,1,0,23,4089

Checking info about the dataset:

In [11]:
avg_annual_daily_direc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1868 entries, 0 to 1867
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   count_point_id                1868 non-null   int64
 1   year                          1868 non-null   int64
 2   region_id                     1868 non-null   int64
 3   region_name                   1868 non-null   object
 4   local_authority_id            1868 non-null   int64
 5   local_authority_name          1868 non-null   object
 6   road_name                     1868 non-null   object
 7   road_type                     1868 non-null   object
 8   start_junction_road_name      1279 non-null   object
 9   end_junction_road_name        1279 non-null   object
 10  easting                       1868 non-null   int64
 11  northing                      1868 non-null   int64
 12  latitude                      1868 non-null   float64
 13  longitude                     1868 non-null   float64
 14  link_length_km                1279 non-null   float64
 15  link_length_miles             1279 non-null   float64
 16  estimation_method             1868 non-null   object
 17  estimation_method_detailed    1868 non-null   object
 18  direction_of_travel           1868 non-null   object
 19  pedal_cycles                  1868 non-null   int64
 20  two_wheeled_motor_vehicles    1868 non-null   int64
 21  cars_and_taxis                1868 non-null   int64
 22  buses_and_coaches             1868 non-null   int64
 23  lgvs                          1868 non-null   int64
 24  hgvs_2_rigid_axle             1868 non-null   int64
 25  hgvs_3_rigid_axle             1868 non-null   int64
 26  hgvs_4_or_more_rigid_axle     1868 non-null   int64
 27  hgvs_3_or_4_articulated_axle  1868 non-null   int64
 28  hgvs_5_articulated_axle       1868 non-null   int64
 29  hgvs_6_articulated_axle       1868 non-null   int64
 30  all_hgvs                      1868 non-null   int64
 31  all_motor_vehicles            1868 non-null   int64
dtypes: float64(4), int64(19), object(9)
memory usage: 467.1+ KB

Checking null values:

In [12]:
avg_annual_daily_direc.isnull().any()

count_point_id                  False
year                            False
region_id                       False
region_name                     False
local_authority_id              False
local_authority_name            False
road_name                       False
road_type                       False
start_junction_road_name         True
end_junction_road_name           True
easting                         False
northing                        False
latitude                        False
longitude                       False
link_length_km                   True
link_length_miles                True
estimation_method               False
estimation_method_detailed      False
direction_of_travel             False
pedal_cycles                    False
two_wheeled_motor_vehicles      False
cars_and_taxis                  False
buses_and_coaches               False
lgvs                            False
hgvs_2_rigid_axle               False
hgvs_3_rigid_axle               False
hgvs_4_or_more_rigid_axle       False
hgvs_3_or_4_articulated_axle    False
hgvs_5_articulated_axle         False
hgvs_6_articulated_axle         False
all_hgvs                        False
all_motor_vehicles              False
dtype: bool

Checking for duplicates:

In [13]:
avg_annual_daily_direc.duplicated().any()

False

Exporting dataset as csv:

In [14]:
#avg_annual_daily_direc.to_csv("C:/Users/ritun/Desktop/MSc Data Science University of Bristol/Data Science Mini Project/CLEANED DATA/Traffic Data/avg_annual_daily_direc.csv")