In [18]:
import pandas as pd
import numpy as np

In [19]:
pd.set_option('display.max_columns', None)

In [20]:
traffic_count_data_scoot=pd.read_csv('C:/Users/ritun/Desktop/MSc Data Science University of Bristol/Data Science Mini Project/Traffic Datasets/Traffic Count Data(SCOOT).csv',delimiter =';',parse_dates=['Date Time'])

In [21]:
traffic_count_data_scoot

,Count Device ID,Date Time,Hourly Flow,Hourly Profile,Description,Full Name,geo_point_2d,Link,Link Direction Lane,Junction
0,100,2021-05-06 22:00:00+01:00,240,168,Bond St EB L2 @ Gloucester St,D02182 - Bond St EB L2 @ Gloucester St,"51.459311,-2.58684",Bond St,Bond St EB L2,Gloucester St
1,256,2021-06-10 18:00:00+01:00,576,592,Parson St OB L1 @ Bedminster Rd,D05233 - Parson St OB L1 @ Bedminster Rd,"51.432602,-2.606828",Parson St,Parson St OB L1,Bedminster Rd
2,204,2020-11-15 11:00:00+00:00,200,280,Bath Rd OB L1 @ Bath Bridge,D04181 - Bath Rd OB L1 @ Bath Bridge,"51.446628,-2.5804968",Bath Rd,Bath Rd OB L1,Bath Bridge
3,278,2021-03-02 19:00:00+00:00,120,112,Parson St EB @ Hartcliffe Way,D05267 - Parson St EB @ Hartcliffe Way,"51.431153,-2.6050694",Parson St,Parson St EB,Hartcliffe Way
4,2,2021-01-02 13:00:00+00:00,48,88,The Grove WB Ln1 @ Prince St,D01112 - The Grove WB Ln1 @ Prince St,"51.449528,-2.5965436",The Grove,The Grove WB Ln1,Prince St
...,...,...,...,...,...,...,...,...,...,...
8488332,444,2022-02-11 06:00:00+00:00,80,96,Wells Rd OB @ Callington Rd,D14161 - Wells Rd OB @ Callington Rd,"51.427642,-2.5637357",Wells Rd,Wells Rd OB,Callington Rd
8488333,370,2022-02-11 16:00:00+00:00,536,568,Fishponds Rd OB @ Beechwood Rd,D12292 - Fishponds Rd OB @ Beechwood Rd,"51.480821,-2.5290398",Fishponds Rd,Fishponds Rd OB,Beechwood Rd
8488334,734,2022-02-11 20:00:00+00:00,416,448,ValeLn Toucan @ HartcliffeWay NB,D05292 - ValeLn Toucan @ HartcliffeWay NB,"51.42893,-2.60442",ValeLn Toucan,ValeLn Toucan,HartcliffeWay NB
8488335,376,2022-02-11 16:00:00+00:00,504,504,Fishponds Rd IB L1 @ Manor Rd,D12315 - Fishponds Rd IB L1 @ Manor Rd,"51.481453,-2.527853",Fishponds Rd,Fishponds Rd IB L1,Manor Rd
8488336,153,2022-02-11 08:00:00+00:00,216,160,Croydon St IB L2 @ Lawrence Hill,D03272 - Croydon St IB L2 @ Lawrence Hill,"51.458247,-2.568339",Croydon St,Croydon St IB L2,Lawrence Hill

In [5]:
#list(zip(traffic_count_data_scoot['Date Time'].iloc[:10], pd.to_datetime(traffic_count_data_scoot['Date Time'].iloc[:10])))

In [8]:
#pd.to_datetime(traffic_count_data_scoot['Date Time'].iloc[0])

In [6]:
#import datetime

#isinstance(traffic_count_data_scoot['Date Time'].iloc[:10], datetime.datetime)

Checking info about the dataset:

In [27]:
traffic_count_data_scoot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8488337 entries, 0 to 8488336
Data columns (total 10 columns):
 #   Column               Dtype
---  ------               -----
 0   Count Device ID      int64
 1   Date Time            object
 2   Hourly Flow          int64
 3   Hourly Profile       int64
 4   Description          object
 5   Full Name            object
 6   geo_point_2d         object
 7   Link                 object
 8   Link Direction Lane  object
 9   Junction             object
dtypes: int64(3), object(7)
memory usage: 647.6+ MB

In [23]:
traffic_count_data_scoot.shape

(8488337, 10)

In [26]:
type(traffic_count_data_scoot['Date Time'].iloc[0])

datetime.datetime

In [28]:
traffic_count_data_scoot.isnull().any()

Count Device ID        False
Date Time              False
Hourly Flow            False
Hourly Profile         False
Description             True
Full Name               True
geo_point_2d            True
Link                    True
Link Direction Lane     True
Junction                True
dtype: bool

In [29]:
traffic_count_data_scoot[traffic_count_data_scoot.geo_point_2d.isnull()]

,Count Device ID,Date Time,Hourly Flow,Hourly Profile,Description,Full Name,geo_point_2d,Link,Link Direction Lane,Junction
15,34,2021-02-03 11:00:00+00:00,344,472,NaN,NaN,NaN,NaN,NaN,NaN
40,65,2021-05-24 18:00:00+01:00,312,304,NaN,NaN,NaN,NaN,NaN,NaN
50,34,2020-11-06 02:00:00+00:00,40,88,NaN,NaN,NaN,NaN,NaN,NaN
53,779,2021-04-22 06:00:00+01:00,64,0,NaN,NaN,NaN,NaN,NaN,NaN
69,733,2021-01-27 03:00:00+00:00,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
8488103,731,2022-02-11 09:00:00+00:00,160,144,NaN,NaN,NaN,NaN,NaN,NaN
8488106,68,2022-02-11 16:00:00+00:00,536,512,NaN,NaN,NaN,NaN,NaN,NaN
8488120,310,2022-02-11 16:00:00+00:00,208,192,NaN,NaN,NaN,NaN,NaN,NaN
8488190,65,2022-02-12 00:00:00+00:00,264,200,NaN,NaN,NaN,NaN,NaN,NaN
8488297,152,2022-02-11 12:00:00+00:00,664,672,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
traffic_count_data_scoot.dropna(subset=['geo_point_2d']).isnull().any()

Count Device ID        False
Date Time              False
Hourly Flow            False
Hourly Profile         False
Description            False
Full Name              False
geo_point_2d           False
Link                   False
Link Direction Lane    False
Junction                True
dtype: bool

Therefore, the rows with missing geopoints have everything except Count Device ID,Date Time,Hourly Flow and Hourly Profile,also missing. These rows are about 2% of the dataset. Still keeping them as we can estimate their location based on their hourly flow.

In [31]:
traffic_count_data_scoot[traffic_count_data_scoot.Junction.isnull()]

,Count Device ID,Date Time,Hourly Flow,Hourly Profile,Description,Full Name,geo_point_2d,Link,Link Direction Lane,Junction
10,172,2020-02-24 06:00:00+00:00,104,96,Redcliffe Way Ln2 after bus gate,D04122 - Redcliffe Way Ln2 after bus gate,"51.448941,-2.5855578",Redcliffe Way,Redcliffe Way Ln2 after bus gate,NaN
15,34,2021-02-03 11:00:00+00:00,344,472,NaN,NaN,NaN,NaN,NaN,NaN
32,517,2020-07-16 06:00:00+01:00,120,88,Callington Rd EB L2 West Town Ln,D24115 - Callington Rd EB L2 West Town Ln,"51.431628,-2.548976",Callington Rd,Callington Rd EB L2 West Town Ln,NaN
40,65,2021-05-24 18:00:00+01:00,312,304,NaN,NaN,NaN,NaN,NaN,NaN
42,515,2020-11-10 18:00:00+00:00,296,288,Callington Rd EB L1 West Town Ln,D24114 - Callington Rd EB L1 West Town Ln,"51.43165,-2.548976",Callington Rd,Callington Rd EB L1 West Town Ln,NaN
...,...,...,...,...,...,...,...,...,...,...
8488146,57,2022-02-11 22:00:00+00:00,0,0,Explore Lane Left Turn,D01313 - Explore Lane Left Turn,"51.450668,-2.6013123",Explore Lane,Explore Lane Left Turn,NaN
8488171,57,2022-02-11 21:00:00+00:00,0,0,Explore Lane Left Turn,D01313 - Explore Lane Left Turn,"51.450668,-2.6013123",Explore Lane,Explore Lane Left Turn,NaN
8488190,65,2022-02-12 00:00:00+00:00,264,200,NaN,NaN,NaN,NaN,NaN,NaN
8488213,173,2022-02-11 18:00:00+00:00,48,24,Redcliffe Way Ln1 befor bus gate,D04123 - Redcliffe Way Ln1 befor bus gate,"51.449013,-2.5873",Redcliffe Way,Redcliffe Way Ln1 befor bus gate,NaN
8488297,152,2022-02-11 12:00:00+00:00,664,672,NaN,NaN,NaN,NaN,NaN,NaN

Checking for duplicates:

In [32]:
traffic_count_data_scoot.duplicated().any()

False

In [33]:
traffic_count_data_scoot

,Count Device ID,Date Time,Hourly Flow,Hourly Profile,Description,Full Name,geo_point_2d,Link,Link Direction Lane,Junction
0,100,2021-05-06 22:00:00+01:00,240,168,Bond St EB L2 @ Gloucester St,D02182 - Bond St EB L2 @ Gloucester St,"51.459311,-2.58684",Bond St,Bond St EB L2,Gloucester St
1,256,2021-06-10 18:00:00+01:00,576,592,Parson St OB L1 @ Bedminster Rd,D05233 - Parson St OB L1 @ Bedminster Rd,"51.432602,-2.606828",Parson St,Parson St OB L1,Bedminster Rd
2,204,2020-11-15 11:00:00+00:00,200,280,Bath Rd OB L1 @ Bath Bridge,D04181 - Bath Rd OB L1 @ Bath Bridge,"51.446628,-2.5804968",Bath Rd,Bath Rd OB L1,Bath Bridge
3,278,2021-03-02 19:00:00+00:00,120,112,Parson St EB @ Hartcliffe Way,D05267 - Parson St EB @ Hartcliffe Way,"51.431153,-2.6050694",Parson St,Parson St EB,Hartcliffe Way
4,2,2021-01-02 13:00:00+00:00,48,88,The Grove WB Ln1 @ Prince St,D01112 - The Grove WB Ln1 @ Prince St,"51.449528,-2.5965436",The Grove,The Grove WB Ln1,Prince St
...,...,...,...,...,...,...,...,...,...,...
8488332,444,2022-02-11 06:00:00+00:00,80,96,Wells Rd OB @ Callington Rd,D14161 - Wells Rd OB @ Callington Rd,"51.427642,-2.5637357",Wells Rd,Wells Rd OB,Callington Rd
8488333,370,2022-02-11 16:00:00+00:00,536,568,Fishponds Rd OB @ Beechwood Rd,D12292 - Fishponds Rd OB @ Beechwood Rd,"51.480821,-2.5290398",Fishponds Rd,Fishponds Rd OB,Beechwood Rd
8488334,734,2022-02-11 20:00:00+00:00,416,448,ValeLn Toucan @ HartcliffeWay NB,D05292 - ValeLn Toucan @ HartcliffeWay NB,"51.42893,-2.60442",ValeLn Toucan,ValeLn Toucan,HartcliffeWay NB
8488335,376,2022-02-11 16:00:00+00:00,504,504,Fishponds Rd IB L1 @ Manor Rd,D12315 - Fishponds Rd IB L1 @ Manor Rd,"51.481453,-2.527853",Fishponds Rd,Fishponds Rd IB L1,Manor Rd
8488336,153,2022-02-11 08:00:00+00:00,216,160,Croydon St IB L2 @ Lawrence Hill,D03272 - Croydon St IB L2 @ Lawrence Hill,"51.458247,-2.568339",Croydon St,Croydon St IB L2,Lawrence Hill

In [75]:
traffic_count_data_scoot[['latitude','longitude']] = traffic_count_data_scoot.geo_point_2d.str.split(",",expand=True,)

In [76]:
traffic_count_data_scoot.latitude = traffic_count_data_scoot.latitude.astype(float)

In [77]:
traffic_count_data_scoot.longitude = traffic_count_data_scoot.longitude.astype(float)

In [79]:
traffic_count_data_scoot.loc[2:3,'longitude'].values

array([-2.5804968, -2.6050694])

In [78]:
traffic_count_data_scoot

,Count Device ID,Date Time,Hourly Flow,Hourly Profile,Description,Full Name,geo_point_2d,Link,Link Direction Lane,Junction,latitude,longitude
0,100,2021-05-06 22:00:00+01:00,240,168,Bond St EB L2 @ Gloucester St,D02182 - Bond St EB L2 @ Gloucester St,"51.459311,-2.58684",Bond St,Bond St EB L2,Gloucester St,51.459311,-2.586840
1,256,2021-06-10 18:00:00+01:00,576,592,Parson St OB L1 @ Bedminster Rd,D05233 - Parson St OB L1 @ Bedminster Rd,"51.432602,-2.606828",Parson St,Parson St OB L1,Bedminster Rd,51.432602,-2.606828
2,204,2020-11-15 11:00:00+00:00,200,280,Bath Rd OB L1 @ Bath Bridge,D04181 - Bath Rd OB L1 @ Bath Bridge,"51.446628,-2.5804968",Bath Rd,Bath Rd OB L1,Bath Bridge,51.446628,-2.580497
3,278,2021-03-02 19:00:00+00:00,120,112,Parson St EB @ Hartcliffe Way,D05267 - Parson St EB @ Hartcliffe Way,"51.431153,-2.6050694",Parson St,Parson St EB,Hartcliffe Way,51.431153,-2.605069
4,2,2021-01-02 13:00:00+00:00,48,88,The Grove WB Ln1 @ Prince St,D01112 - The Grove WB Ln1 @ Prince St,"51.449528,-2.5965436",The Grove,The Grove WB Ln1,Prince St,51.449528,-2.596544
...,...,...,...,...,...,...,...,...,...,...,...,...
8488332,444,2022-02-11 06:00:00+00:00,80,96,Wells Rd OB @ Callington Rd,D14161 - Wells Rd OB @ Callington Rd,"51.427642,-2.5637357",Wells Rd,Wells Rd OB,Callington Rd,51.427642,-2.563736
8488333,370,2022-02-11 16:00:00+00:00,536,568,Fishponds Rd OB @ Beechwood Rd,D12292 - Fishponds Rd OB @ Beechwood Rd,"51.480821,-2.5290398",Fishponds Rd,Fishponds Rd OB,Beechwood Rd,51.480821,-2.529040
8488334,734,2022-02-11 20:00:00+00:00,416,448,ValeLn Toucan @ HartcliffeWay NB,D05292 - ValeLn Toucan @ HartcliffeWay NB,"51.42893,-2.60442",ValeLn Toucan,ValeLn Toucan,HartcliffeWay NB,51.428930,-2.604420
8488335,376,2022-02-11 16:00:00+00:00,504,504,Fishponds Rd IB L1 @ Manor Rd,D12315 - Fishponds Rd IB L1 @ Manor Rd,"51.481453,-2.527853",Fishponds Rd,Fishponds Rd IB L1,Manor Rd,51.481453,-2.527853
8488336,153,2022-02-11 08:00:00+00:00,216,160,Croydon St IB L2 @ Lawrence Hill,D03272 - Croydon St IB L2 @ Lawrence Hill,"51.458247,-2.568339",Croydon St,Croydon St IB L2,Lawrence Hill,51.458247,-2.568339

Therefore, we can see that on converting the longitude and latitude values to floar, the dataframe shows some rounding off but printing them using iloc shows the actual value without rounding. Therefore, the float conversion is correct

In [82]:
traffic_count_data_scoot.rename(columns = {'Count Device ID' : 'count_device_id', 'Date Time' : 'date_time',
                                           'Hourly Flow':'hourly_flow','Hourly Profile':'hourly_profile',
                                           'Description':'description','Full Name':'full_name','Link':'link',
                                           'Link Direction Lane':'link_direction_lane','Junction':'junction'}, inplace = True)

In [83]:
traffic_count_data_scoot

,count_device_id,date_time,hourly_flow,hourly_profile,description,full_name,geo_point_2d,link,link_direction_lane,junction,latitude,longitude
0,100,2021-05-06 22:00:00+01:00,240,168,Bond St EB L2 @ Gloucester St,D02182 - Bond St EB L2 @ Gloucester St,"51.459311,-2.58684",Bond St,Bond St EB L2,Gloucester St,51.459311,-2.586840
1,256,2021-06-10 18:00:00+01:00,576,592,Parson St OB L1 @ Bedminster Rd,D05233 - Parson St OB L1 @ Bedminster Rd,"51.432602,-2.606828",Parson St,Parson St OB L1,Bedminster Rd,51.432602,-2.606828
2,204,2020-11-15 11:00:00+00:00,200,280,Bath Rd OB L1 @ Bath Bridge,D04181 - Bath Rd OB L1 @ Bath Bridge,"51.446628,-2.5804968",Bath Rd,Bath Rd OB L1,Bath Bridge,51.446628,-2.580497
3,278,2021-03-02 19:00:00+00:00,120,112,Parson St EB @ Hartcliffe Way,D05267 - Parson St EB @ Hartcliffe Way,"51.431153,-2.6050694",Parson St,Parson St EB,Hartcliffe Way,51.431153,-2.605069
4,2,2021-01-02 13:00:00+00:00,48,88,The Grove WB Ln1 @ Prince St,D01112 - The Grove WB Ln1 @ Prince St,"51.449528,-2.5965436",The Grove,The Grove WB Ln1,Prince St,51.449528,-2.596544
...,...,...,...,...,...,...,...,...,...,...,...,...
8488332,444,2022-02-11 06:00:00+00:00,80,96,Wells Rd OB @ Callington Rd,D14161 - Wells Rd OB @ Callington Rd,"51.427642,-2.5637357",Wells Rd,Wells Rd OB,Callington Rd,51.427642,-2.563736
8488333,370,2022-02-11 16:00:00+00:00,536,568,Fishponds Rd OB @ Beechwood Rd,D12292 - Fishponds Rd OB @ Beechwood Rd,"51.480821,-2.5290398",Fishponds Rd,Fishponds Rd OB,Beechwood Rd,51.480821,-2.529040
8488334,734,2022-02-11 20:00:00+00:00,416,448,ValeLn Toucan @ HartcliffeWay NB,D05292 - ValeLn Toucan @ HartcliffeWay NB,"51.42893,-2.60442",ValeLn Toucan,ValeLn Toucan,HartcliffeWay NB,51.428930,-2.604420
8488335,376,2022-02-11 16:00:00+00:00,504,504,Fishponds Rd IB L1 @ Manor Rd,D12315 - Fishponds Rd IB L1 @ Manor Rd,"51.481453,-2.527853",Fishponds Rd,Fishponds Rd IB L1,Manor Rd,51.481453,-2.527853
8488336,153,2022-02-11 08:00:00+00:00,216,160,Croydon St IB L2 @ Lawrence Hill,D03272 - Croydon St IB L2 @ Lawrence Hill,"51.458247,-2.568339",Croydon St,Croydon St IB L2,Lawrence Hill,51.458247,-2.568339

In [84]:
#traffic_count_data_scoot.to_csv("C:/Users/ritun/Desktop/MSc Data Science University of Bristol/Data Science Mini Project/CLEANED DATA/Traffic Data/traffic_count_data_scoot.csv")

In [ ]:
# The times are parsed and already in datetime(we can see that by converting to date_time individually.
#Also, the time is in terms of UTC.Note that the values are UTC+00:00 and UTC+0100. UTC and BST are same 
#in winters(UTC is 5.5 hours behind IST) so +00:00 and in summers there is a gap of 1 hour (BST is 4.5 behing IST) 
#between UTC and BST so +0100