In [52]:
import pandas as pd
import numpy as np

In [53]:
pd.set_option('display.max_columns', None)

In [54]:
traffic_annual=pd.read_csv('C:/Users/ritun/Desktop/MSc Data Science University of Bristol/Data Science Mini Project/Traffic Datasets/Bristol Traffic Data/Traffic (Annual) - Copy.csv')

In [55]:
traffic_annual=traffic_annual.set_index("year").sort_index()

In [56]:
traffic_annual.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28 entries, 1993 to 2020
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   local_authority_id    28 non-null     int64
 1   local_authority_name  28 non-null     object
 2   link_length_km        28 non-null     float64
 3   link_length_miles     28 non-null     float64
 4   cars_and_taxis        28 non-null     int64
 5   all_motor_vehicles    28 non-null     int64
dtypes: float64(2), int64(3), object(1)
memory usage: 1.5+ KB

In [57]:
traffic_annual

,local_authority_id,local_authority_name,link_length_km,link_length_miles,cars_and_taxis,all_motor_vehicles
year,,,,,,
1993,144,"Bristol, City of",1103.676000,685.79,1028594049,1223835699
1994,144,"Bristol, City of",1106.598000,687.61,1040769028,1240399499
1995,144,"Bristol, City of",1109.500000,689.41,1057059128,1260685812
1996,144,"Bristol, City of",1112.469000,691.26,1059073575,1266820928
1997,144,"Bristol, City of",1115.835000,693.35,1063496566,1278335695
1998,144,"Bristol, City of",1118.788000,695.18,1075833118,1297075285
1999,144,"Bristol, City of",1122.700000,697.61,1078738016,1302710004
2000,144,"Bristol, City of",1125.400000,699.29,1088005264,1314386742
2001,144,"Bristol, City of",1128.300000,701.09,1103451273,1331817271
2002,144,"Bristol, City of",1129.800000,702.03,1135675456,1369734358
2003,144,"Bristol, City of",1132.763500,703.87,1117247856,1366099697
2004,144,"Bristol, City of",1129.400000,701.78,1131984379,1387216770
2005,144,"Bristol, City of",1131.600000,703.14,1132346951,1393128469
2006,144,"Bristol, City of",1135.900000,705.82,1142473586,1404861057
2007,144,"Bristol, City of",1137.700000,706.93,1167497426,1444681808
2008,144,"Bristol, City of",1142.000000,709.61,1165310481,1436740885
2009,144,"Bristol, City of",1140.700000,708.80,1161074750,1424189058
2010,144,"Bristol, City of",1140.500000,708.67,1128163590,1390833927
2011,144,"Bristol, City of",1143.100000,710.29,1150053123,1415335926
2012,144,"Bristol, City of",1145.410596,711.73,1153982267,1419279354
2013,144,"Bristol, City of",1144.919064,711.42,1151989963,1422398055
2014,144,"Bristol, City of",1150.980000,715.19,1182318547,1468437219
2015,144,"Bristol, City of",1152.830000,716.34,1186972252,1480575078
2016,144,"Bristol, City of",1153.440000,716.71,1185934973,1487084127
2017,144,"Bristol, City of",1155.800000,718.18,1206777662,1508593562
2018,144,"Bristol, City of",1162.399200,722.28,1207830535,1504528681
2019,144,"Bristol, City of",1163.579000,723.01,1218315126,1515001514
2020,144,"Bristol, City of",1165.251000,724.05,931680702,1184815061

In [58]:
#traffic_annual.to_csv("C:/Users/ritun/Desktop/MSc Data Science University of Bristol/Data Science Mini Project/CLEANED DATA/Traffic Data/traffic_annual_cleaned.csv")